### ISSUE TITLE
Razorpay integration Backend

### ISSUE THREAD

**Issue by Jenin82** [gtech-mulearn/mulearnbackend#1899]

**Comment by Jenin82** [comment]
Razorpay integration [Documentation](https://razorpay.com/docs/api/orders/create/)

**Comment by Mishalabdullah** [comment]
@Jenin82 I do need the key id and secerect from the razor pay account 

```json
curl -u [YOUR_KEY_ID]:[YOUR_KEY_SECRET] \
-X POST https://api.razorpay.com/v1/orders \
-H "content-type: application/json" \
-d '{
  "amount": 50000,
  "currency": "INR",
  "receipt": "receipt#1",
  "notes": {
    "key1": "value3",
    "key2": "value2"
  }
}'
```

**Comment by Jenin82** [comment]
@Mishalabdullah I'll get it to you as soon as possible, already contacted @shaheenhyderk to provide it

**Comment by Jenin82** [comment]
@Mishalabdullah i found out that we actually dont need backend for our purpose so im closing this issue
